### ISSUE TITLE
reconciler调度模块是不是应该详细介绍下呢

### ISSUE THREAD

**Issue by zhang14725804** [BetaSu/react-on-the-way#3]
如题，reconciler模块架构思路应该介绍下，要不然懂的人懒得看，不懂的人一头雾水，比如我

**Comment by BetaSu** [comment]
🤭  整个系列正在重新写。  单纯md格式比较受限，会 辅助加上 动画、视频等。

**Comment by zhang14725804** [comment]
那的什么时候才能完，工作量不小呢

**Comment by BetaSu** [comment]
I have no idea, just try hard~~

**Comment by zhang14725804** [comment]
可以从v1开始，每个版本设计到的功能点知识点逻辑架构，这样比直接大水漫灌相对有好一些

**Comment by BetaSu** [comment]
文章更新了

**Comment by BetaSu** [comment]
文章更新了， 有任何疑问欢迎PR， 感谢🙏
https://betasu.github.io/just-react/

**Comment by zhang14725804** [comment]
> 文章更新了， 有任何疑问欢迎PR， 感谢
> https://betasu.github.io/just-react/

不错不错，奥利给
